config/routes.rb
Projectx::Engine.routes.draw do

  #resources :misc_definitions
  resources :task_definitions  
  #resources :logs, :only => [:index]
  resources :contracts, :only => [:index]  
  resources :projects do
    resources :contracts, :only => [:index, :edit, :update, :show]
    resources :tasks
    resources :logs
 
    collection do
      get :search
      put :search_results
      get :stats
      put :stats_results    
    end
  end
  resources :payments, :only => [:index] 
  resources :contracts do
    resources :payments
    collection do
      get :search
      put :search_results
      get :stats
      put :stats_results
      #get :autocomplete
    end
  end
  resources :payments do
    collection do
      get :search
      put :search_results
      get :stats
      put :stats_results
      #get :autocomplete
    end
  end
  
  resources :task_requests, :only => [:index]
  resources :tasks do
    resources :task_requests
    #resources :logs
  end
  
  #resources :task_requests do
  #  resources :logs
  #end
  
  resources :project_task_templates, :only => [:index]
  resources :type_definitions do
    resources :project_task_templates
  end
  resources :task_templates, :only => [:index]
  resources :project_task_templates do
    resources :task_templates
  end
end

app/controllers/projectx/application_controller.rb
# encoding: utf-8
module Projectx
  class Projectx::ApplicationController < ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Searchx::SearchHelper
    
    include Commonx::CommonxHelper
    include Projectx::ProjectxHelper

    helper_method :return_task_definitions  
     
    before_filter :require_signin 
    before_filter :max_pagination   
    before_filter :check_access_right
    before_filter :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_filter :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right

=begin
    def search
      @title = params[:controller].camelize.demodulize.tableize.singularize.capitalize + ' Search'  
      @model, @search_stat = Commonx::CommonxHelper.search(params)
      @results_url = 'search_results_' + params[:controller].camelize.demodulize.tableize.downcase + '_path'
      @erb_code = find_config_const('search_params_view')
    end

    def search_results
      @title = params[:controller].camelize.demodulize.tableize.singularize.capitalize + ' Search'
      @s_s_results_details =  Commonx::CommonxHelper.search_results(params, @max_pagination)
      @erb_code = find_config_const(params[:controller].camelize.demodulize.tableize.singularize.downcase + '_index_view', params[:controller].camelize.deconstantize.tableize.singularize.downcase)
    end
    
    def stats
      @title = params[:controller].camelize.demodulize.tableize.singularize.capitalize + ' Stats' 
      @model, @search_stat = Commonx::CommonxHelper.search(params)
      @results_url = 'stats_results_' + params[:controller].camelize.demodulize.tableize.downcase + '_path'
      @erb_code = find_config_const('stats_params_view')
    end

    def stats_results
      @title = params[:controller].camelize.demodulize.tableize.singularize.capitalize + ' Stats' 
      @s_s_results_details =  Commonx::CommonxHelper.search_results(params, @max_pagination)
      @time_frame = eval(@s_s_results_details.time_frame)
      @erb_code = find_config_const(params[:controller].camelize.demodulize.tableize.singularize.downcase + '_index_view', params[:controller].camelize.deconstantize.tableize.singularize.downcase)
    end
=end
    def max_pagination
      @max_pagination = find_config_const('pagination').to_i
    end

  end
end

app/controllers/projectx/contracts_controller.rb
# encoding: utf-8
require_dependency "projectx/application_controller"

module Projectx
  class ContractsController < ApplicationController
    
    prepend_before_filter :require_employee
    before_filter :load_project


    def index
      @title = 'Contracts'
      if @project
        @contracts = Projectx::Contract.where(:project_id => @project.id).page(params[:page]).per_page(@max_pagination)  #@project.contract has pagination error
      else
        @contracts = params[:projectx_contracts][:model_ar_r].page(params[:page]).per_page(@max_pagination)
      end
    end

    def edit
      @title = 'Edit Contract'
      @contract = Projectx::Contract.find_by_id(params[:id])
    end

    def update
      @contract = Projectx::Contract.find_by_id(params[:id])
      @contract.last_updated_by_id = session[:user_id]
      if @contract.update_attributes(params[:contract], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Contract Successfully Updated!")
      else
        flash.now[:error] = t('Data Error. Contract Not Updated!')
        render 'edit'
      end
    end


    def show
      @title = 'Contract Info'
      @contract = Projectx::Contract.find_by_id(params[:id])
    end


    protected


    def load_project
      @project = Projectx::Project.find_by_id(params[:project_id]) if params[:project_id].present? && params[:project_id].to_i > 0
    end


  end
end

app/controllers/projectx/payments_controller.rb
require_dependency "projectx/application_controller"

module Projectx
  class PaymentsController < ApplicationController
    prepend_before_filter :require_employee
    before_filter :load_contract


    def index
      @title = 'Payments'
      if @contract
        @payments = @contract.payments.page(params[:page]).per_page(@max_pagination)
      else
        @payments = params[:projectx_payments][:model_ar_r].page(params[:page]).per_page(@max_pagination)
      end
      @erb_code = find_config_const('payment_index_view', 'projectx')
    end


    def new
      @title = 'New Payment'
      @payment = @contract.payments.new
      #@payment.contract_id = params[:contract_id]
    end


    def create
      #@payment = Projectx::Payment.new(params[:payment], :as => :role_new)
      @payment = @contract.payments.new(params[:payment], :as => :role_new)
      @payment.last_updated_by_id = session[:user_id]
      if @payment.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end

    def edit
      @title = 'Edit Payment'
      @payment = Projectx::Payment.find_by_id(params[:id])
    end

    def update
      @payment = Projectx::Payment.find_by_id(params[:id])
      @payment.last_updated_by_id = session[:user_id]
      if @payment.update_attributes(params[:payment], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        flash[:notice] = t('Data Error. No Updated!')
        render 'edit'
      end
    end

    def show
      @title = 'Payment Info'
      @payment = Projectx::Payment.find_by_id(params[:id])
      @erb_code = find_config_const('payment_show_view', 'projectx')
    end

    def autocomplete
      @payments = Projectx::Payment.where("active = ?", true).order(:name).where("name like ?", "%#{params[:term]}%")
      render json: @payments.map(&:name)
    end


    protected
    
    
=begin
    def search_params
      search_params = 'Search Parameters:'
      search_params += ', Contract Id:' + params[:contract_id_s] if params[:contract_id_s].present?
      search_params += ', Received After Date:' + params[:received_after_date_s] if params[:received_after_date_s].present?
      search_params += ', Received Before Date:' + params[:received_before_date_s] if params[:received_before_date_s].present?
      search_params += ', Received By:' + params[:received_by_id_s] if params[:received_by_id_s].present?
      search_params += ', Payed By:' + params[:paid_by_id_s] if params[:paid_by_id_s].present?
      search_params += ', Payment Type' + params[:payment_type_s] if params[:payment_type_s].present?
      search_params
    end


    def apply_search_criteria(payments, params)
      payments = payments.where("id = ?", params[:payment_id_s]) if params[:payment_id_s].present?
      payments = payments.where("contract_id = ?", params[:contract_id_s]) if params[:contract_id_s].present?
      payments = payments.where('received_date > ?', params[:received_after_date_s]) if params[:received_after_date_s].present?
      payments = payments.where('received_date < ?', params[:received_before_date_s]) if params[:received_before_date_s].present?
      payments = payments.where(:received_by_id => params[:received_by_id_s] ) if params[:received_by_id_s].present?
      payments = payments.where(:paid_by_id => params[:paid_by_id_s]) if params[:paid_by_id_s].present?
      payments = payments.where(:payment_type => params[:payment_type_s]) if params[:payment_type_s].present?
      payments
    end
=end

    #def apply_pagination(payments)
    #  max_entries_page = find_config_const('pagination')
     # payments = payments.page(params[:page]).per_page(max_entries_page).order("received_date DESC")
    #  payments.all()
    #end
    
    def load_contract
      @contract = Projectx::Contract.find_by_id(params[:contract_id]) if params[:contract_id].present? && params[:contract_id].to_i > 0
    end

  end
end

app/controllers/projectx/project_task_templates_controller.rb
# encoding: utf-8
require_dependency "projectx/application_controller"

module Projectx
  class ProjectTaskTemplatesController < ApplicationController
    before_filter :require_employee
    before_filter :load_project_type

    helper_method :return_task_definitions
    
    def index
      @title = 'Project Task Templates'
      if @type_definition
        @project_task_templates = @type_definition.project_task_templates.page(params[:page]).per_page(@max_pagination) 
      else
        @project_task_templates = params[:projectx_project_task_templates][:model_ar_r].page(params[:page]).per_page(@max_pagination) 
      end
    end
  
    def new
      @title = 'New Project Task Template'
      @project_task_template = @type_definition.project_task_templates.new()
      @project_task_template.task_templates.build()
    end
  
    def create
      @project_task_template = @type_definition.project_task_templates.new(params[:project_task_template], :as => :role_new)
      @project_task_template.last_updated_by_id = session[:user_id]
      if @project_task_template.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        flash.now[:error] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = 'Edit Project Task Template'
      @project_task_template = Projectx::ProjectTaskTemplate.find_by_id(params[:id])
    end
  
    def update
      @project_task_template = Projectx::ProjectTaskTemplate.find_by_id(params[:id])
      @project_task_template.last_updated_by_id = session[:user_id]
      if @project_task_template.update_attributes(params[:project_task_template], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        flash.now[:error] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = 'Project Task Template Info'
      @project_task_template = Projectx::ProjectTaskTemplate.find_by_id(params[:id])
    end
    
    protected
    def load_project_type
      @type_definition = Projectx::TypeDefinition.find_by_id(params[:type_definition_id]) if params[:type_definition_id].present?
    end
  end
end

app/controllers/projectx/project_templates_controller.rb
# encoding: utf-8
require_dependency "projectx/application_controller"

module Projectx
  class ProjectTemplatesController < ApplicationController
    before_filter :require_employee
    before_filter :load_project_type
    
    def index
      @title = '项目样板一览'
      if @type_definition
        @project_templates = @type_definition.project_templates.page(params[:page]).per_page(30) 
      else
        @project_templates = params[:projectx_project_templates][:model_ar_r].page(params[:page]).per_page(30) 
      end
    end
  
    def new
      @title = '新项目样板'
      @project_template = @type_definition.project_templates.new()
      @project_template.task_templates.build()
    end
  
    def create
      @project_template = @type_definition.project_templates.new(params[:project_template], :as => :role_new)
      @project_template.last_updated_by_id = session[:user_id]
      if @project_template.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=项目样板已保存!")
      else
        flash.now[:error] = 'Data Error. Not Saved!'
        render 'new'
      end
    end
  
    def edit
      @title = '更新项目样板'
      @project_template = Projectx::ProjectTemplate.find_by_id(params[:id])
    end
  
    def update
      @project_template = Projectx::ProjectTemplate.find_by_id(params[:id])
      @project_template.last_updated_by_id = session[:user_id]
      if @project_template.update_attributes(params[:project_template], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=项目样板已更新!")
      else
        flash.now[:error] = 'Data Error. Not Updated!'
        render 'edit'
      end
    end
  
    def show
      @title = '项目样板内容'
      @project_template = Projectx::ProjectTemplate.find_by_id(params[:id])
    end
    
    protected
    def load_project_type
      @type_definition = Projectx::TypeDefinition.find_by_id(params[:type_definition_id]) if params[:type_definition_id].present?
    end
  end
end

app/controllers/projectx/projects_controller.rb
#encoding: utf-8
require_dependency "projectx/application_controller"

module Projectx
  class ProjectsController < ApplicationController
    prepend_before_filter :require_employee


    def index
      @title = 'Projects'
      @projects =  params[:projectx_projects][:model_ar_r].page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('project_index_view', 'projectx')
    end

    def new
      @title = 'New Project'
      @project = Projectx::Project.new
      @project.build_contract
      @erb_code = find_config_const('project_new_view', 'projectx')
    end


    def create
      @project = Projectx::Project.new(params[:project], :as => :role_new)
      @project.last_updated_by_id = session[:user_id]
      if @project.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        flash[:notice] = t('Data Error. Not Saved!')
        @erb_code = find_config_const('project_new_view', 'projectx')
        render 'new'
      end
    end

    def edit
      @title = 'Edit Project'
      @project = Projectx::Project.find_by_id(params[:id])
      @erb_code = find_config_const('project_edit_view', 'projectx')
    end

    def update
        @project = Projectx::Project.find_by_id(params[:id])
        @project.last_updated_by_id = session[:user_id]
        if @project.update_attributes(params[:project], :as => :role_update)
          redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
        else
          flash[:notice] = t('Data Error. Not Updated!')
          @erb_code = find_config_const('project_edit_view', 'projectx')
          render 'edit'
        end
    end

    def show
      @title = 'Project Info'
      @project = Projectx::Project.find_by_id(params[:id])
      @erb_code = find_config_const('project_show_view', 'projectx')
    end




    protected


  end


end

app/controllers/projectx/task_definitions_controller.rb
# encoding: utf-8
require_dependency "projectx/application_controller"

module Projectx
  class TaskDefinitionsController < ApplicationController
    
    prepend_before_filter :require_employee

    def index
      @title = 'Task Definition'
      @task_definitions = params[:projectx_task_definitions][:model_ar_r].page(params[:page]).per_page(@max_pagination)     
    end
  
    def new
      @title = 'New Task Definition'
      @task_definition = Projectx::TaskDefinition.new
    end
  
    def create
      @task_definition = Projectx::TaskDefinition.new(params[:task_definition], :as => :role_new)
      @task_definition.last_updated_by_id = session[:user_id]
      if @task_definition.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        flash.now[:error] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = 'Edit Task Definition'
      @task_definition = Projectx::TaskDefinition.find_by_id(params[:id])
    end
  
    def update
      @task_definition = Projectx::TaskDefinition.find_by_id(params[:id])
      @task_definition.last_updated_by_id = session[:user_id]
      if @task_definition.update_attributes(params[:task_definition], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        flash.now[:error] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
    
  end
end

app/helpers/projectx/application_helper.rb
module Projectx
  module ApplicationHelper
    include Commonx::CommonxHelper
    include Projectx::ProjectxHelper
    include Customerx::CustomerxHelper
    #ActionView::Base.default_form_builder = Projectx::FormBuilderWithMasking   

    #def return_task_status
    #  Commonx::MiscDefinition.where(:active => true).where(:for_which => 'task_status').order('ranking_index')
    #end
  end

end

app/views/projectx/task_definitions/_form.html.erb
<%= simple_form_for @task_definition do |f| %>    
	  <%= f.input :name, :label => t('Task Name'), :readonly => readonly?(@task_definition, 'name') %>  
	  <%= f.input :task_desp, :label => t('Description'), :readonly => readonly?(@task_definition, 'task_desp') %>
	  <%= f.input :task_instruction, :label => t('Instructions'), :input_html => {:rows => 4}, :readonly => readonly?(@task_definition, 'task_instruction') %>
	  <%= f.input :ranking_order, :label => t('Ranking Order'), :readonly => readonly?(@task_definition, 'ranking_order') %>
	  <% if readonly?(@task_definition, 'active')%>
        <%= f.input :active_noupdate, :label => t('Active'), :readonly => true, :required => false, :input_html => {:value => @task_definition.active} %>
      <% else %>
        <%= f.input :active, :label => t('Active'), :collection => [['是', true], ['否', false]]%>
      <% end %>
	  
	  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

app/views/projectx/task_definitions/_form_list.html.erb
    <table class="table table-striped">
		<tr>
			<th><%= t('Task Name') %></th>
			<th><%= t('Description') %></th>
			<th><%= t('Instructions') %></th>
			<th><%= t('Active') %></th>
			<th><%= t('Last Updated By') %></th>
			<th><%= t('Ranking') %></th>
			<th></th>
		</tr>
		<% @task_definitions.each do |defi| %>
		  <tr>
		  	<td><%= defi.name %></td>
			<td><%= prt(defi, :task_desp) %></td>
			<td><%= prt(defi, :task_instruction) %></td>
			<td><%= t(prt(defi, :active).to_s) %></td>
			<td><%= prt(defi, 'last_updated_by.name') %></td>    
			<td><%= prt(defi, :ranking_order) %></td>
			<td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{edit_task_definition_path(defi)}", :class => BUTTONS_CLS['action']  if has_action_right?('update', 'projectx_task_definitions', defi) %></td>
		  </tr>
		<% end %>
	</table>
	
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('New Task Definition'), SUBURI + "/authentify/view_handler?index=1&url=#{new_task_definition_path}", :class => BUTTONS_CLS['action'] if has_action_right?('create','projectx_task_definitions') %>
	    </th>
	  </tr>
	</table>
	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>

app/views/projectx/task_definitions/_form_new.html.erb
<%= simple_form_for @task_definition do |f| %>    
	  <%= f.input :name, :label => t('Task Name') %>  
	  <%= f.input :task_desp, :label => t('Description') %>
	  <%= f.input :task_instruction, :label => t('Instructions'), :input_html => {:rows => 4} %>
	  <%= f.input :ranking_order, :label => t('Ranking Order') %>
	  <%#= f.input :active, :label => t('Active'), :collection => [['是', true], ['否', false]] %>
	  
	  <%= f.button :submit, t('Save'), :class =>'btn btn-primary' %>  
<% end %>  

app/views/projectx/task_definitions/create.html.erb
<h4>Projects#create</h4>
<p>Find me in app/views/task_definitions/create.html.erb</p>

app/views/projectx/task_definitions/edit.html.erb
<div id="main_body">
<h4><%=t('Edit Task Definition Info') %></h4>
 
<%= render 'form'  %>
 
<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
</div>
  
 

app/views/projectx/task_definitions/index.html.erb
<div id="main_body">
	<h4><%=t('Task Definitions') %></h4>
	<div class="pagination"><%= will_paginate @task_definitions %></div>
 
	<%= render 'form_list' %>
 
</div>

app/views/projectx/task_definitions/new.html.erb
<div id="main_body">
<h4><%=t('New Task Definition') %></h4>

<%= render 'form_new' %>

<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
</div>

app/views/projectx/task_definitions/show.html.erb
<div id="main_body">
<h4><%=t('Task Definition Info') %></h4>

<p>
  <b><%= t('Name') %></b>
  <%= @task_definition.name %>
</p>
<p>
  <b><%= t('Description') %></b>
  <%= @task_definition.task_desp %>
</p>
<p>
  <b><%= t('Instructions') %></b>
  <%= @task_definition.task_instruction %>
</p>
<p>
  <b><%= t('Ranking') %></b>
  <%= @task_definition.ranking_order %>
</p>
<p>
  <b><%= t('Active') %></b>
  <%= @task_definition.active %>
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @task_definition.last_updated_by.name %>
</p>

  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>

</div>

app/views/projectx/task_definitions/update.html.erb
<h4>Projects#update</h4>
<p>Find me in app/views/task_definitions/update.html.erb</p>